<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<doxygen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="compound.xsd" version="1.8.11">
  <compounddef id="classtranslator__client_1_1exceptions_1_1ApiValueError" kind="class" language="Python" prot="public">
    <compoundname>translator_client::exceptions::ApiValueError</compoundname>
    <basecompoundref refid="classtranslator__client_1_1exceptions_1_1OpenApiException" prot="public" virt="non-virtual">translator_client.exceptions.OpenApiException</basecompoundref>
    <basecompoundref prot="public" virt="non-virtual">ValueError</basecompoundref>
    <basecompoundref refid="classtranslator__client_1_1exceptions_1_1OpenApiException" prot="public" virt="non-virtual">translator_client.exceptions.OpenApiException</basecompoundref>
    <basecompoundref prot="public" virt="non-virtual">ValueError</basecompoundref>
      <sectiondef kind="public-attrib">
      <memberdef kind="variable" id="classtranslator__client_1_1exceptions_1_1ApiValueError_1ad22c4e5d86cd9b347698e9cb37f6561b" prot="public" static="no" mutable="no">
        <type></type>
        <definition>translator_client.exceptions.ApiValueError::path_to_item</definition>
        <argsstring></argsstring>
        <name>path_to_item</name>
        <briefdescription>
        </briefdescription>
        <detaileddescription>
        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="OpenAPI/tests/editable_copies/translator_client/translator_client/exceptions.py" line="60" column="1" bodyfile="OpenAPI/tests/editable_copies/translator_client/translator_client/exceptions.py" bodystart="60" bodyend="-1"/>
      </memberdef>
      </sectiondef>
      <sectiondef kind="public-func">
      <memberdef kind="function" id="classtranslator__client_1_1exceptions_1_1ApiValueError_1a7d6f47101d6e223580b0da8c9d8a1954" prot="public" static="no" const="no" explicit="no" inline="no" virt="non-virtual">
        <type>def</type>
        <definition>def translator_client.exceptions.ApiValueError.__init__</definition>
        <argsstring>(self, msg, path_to_item=None)</argsstring>
        <name>__init__</name>
        <param>
          <type>self</type>
          <defname>self</defname>
        </param>
        <param>
          <type>msg</type>
          <defname>msg</defname>
        </param>
        <param>
          <type>path_to_item</type>
          <defname>path_to_item</defname>
          <defval>None</defval>
        </param>
        <briefdescription>
        </briefdescription>
        <detaileddescription>
<para><verbatim>Args:
    msg (str): the exception message

Keyword Args:
    path_to_item (list) the path to the exception in the
received_data dict. None if unset
</verbatim> </para>        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="OpenAPI/tests/editable_copies/translator_client/translator_client/exceptions.py" line="50" column="1" bodyfile="OpenAPI/tests/editable_copies/translator_client/translator_client/exceptions.py" bodystart="50" bodyend="66"/>
      </memberdef>
      <memberdef kind="function" id="classtranslator__client_1_1exceptions_1_1ApiValueError_1a7d6f47101d6e223580b0da8c9d8a1954" prot="public" static="no" const="no" explicit="no" inline="no" virt="non-virtual">
        <type>def</type>
        <definition>def translator_client.exceptions.ApiValueError.__init__</definition>
        <argsstring>(self, msg, path_to_item=None)</argsstring>
        <name>__init__</name>
        <param>
          <type>self</type>
          <defname>self</defname>
        </param>
        <param>
          <type>msg</type>
          <defname>msg</defname>
        </param>
        <param>
          <type>path_to_item</type>
          <defname>path_to_item</defname>
          <defval>None</defval>
        </param>
        <briefdescription>
        </briefdescription>
        <detaileddescription>
<para><verbatim>Args:
    msg (str): the exception message

Keyword Args:
    path_to_item (list) the path to the exception in the
received_data dict. None if unset
</verbatim> </para>        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="OpenAPI/tests/translator_client/translator_client/exceptions.py" line="50" column="1" bodyfile="OpenAPI/tests/translator_client/translator_client/exceptions.py" bodystart="50" bodyend="66"/>
      </memberdef>
      </sectiondef>
    <briefdescription>
    </briefdescription>
    <detaileddescription>
    </detaileddescription>
    <inheritancegraph>
      <node id="2072">
        <label>translator_client.exceptions.OpenApiException</label>
        <link refid="classtranslator__client_1_1exceptions_1_1OpenApiException"/>
        <childnode refid="2073" relation="public-inheritance">
        </childnode>
        <childnode refid="2073" relation="public-inheritance">
        </childnode>
      </node>
      <node id="2071">
        <label>translator_client.exceptions.ApiValueError</label>
        <link refid="classtranslator__client_1_1exceptions_1_1ApiValueError"/>
        <childnode refid="2072" relation="public-inheritance">
        </childnode>
        <childnode refid="2074" relation="public-inheritance">
        </childnode>
        <childnode refid="2072" relation="public-inheritance">
        </childnode>
        <childnode refid="2074" relation="public-inheritance">
        </childnode>
      </node>
      <node id="2074">
        <label>ValueError</label>
      </node>
      <node id="2073">
        <label>Exception</label>
      </node>
    </inheritancegraph>
    <collaborationgraph>
      <node id="2076">
        <label>translator_client.exceptions.OpenApiException</label>
        <link refid="classtranslator__client_1_1exceptions_1_1OpenApiException"/>
        <childnode refid="2077" relation="public-inheritance">
        </childnode>
        <childnode refid="2077" relation="public-inheritance">
        </childnode>
      </node>
      <node id="2075">
        <label>translator_client.exceptions.ApiValueError</label>
        <link refid="classtranslator__client_1_1exceptions_1_1ApiValueError"/>
        <childnode refid="2076" relation="public-inheritance">
        </childnode>
        <childnode refid="2078" relation="public-inheritance">
        </childnode>
        <childnode refid="2076" relation="public-inheritance">
        </childnode>
        <childnode refid="2078" relation="public-inheritance">
        </childnode>
      </node>
      <node id="2078">
        <label>ValueError</label>
      </node>
      <node id="2077">
        <label>Exception</label>
      </node>
    </collaborationgraph>
    <location file="OpenAPI/tests/editable_copies/translator_client/translator_client/exceptions.py" line="49" column="1" bodyfile="OpenAPI/tests/editable_copies/translator_client/translator_client/exceptions.py" bodystart="49" bodyend="67"/>
    <listofallmembers>
      <member refid="classtranslator__client_1_1exceptions_1_1ApiValueError_1a7d6f47101d6e223580b0da8c9d8a1954" prot="public" virt="non-virtual"><scope>translator_client::exceptions::ApiValueError</scope><name>__init__</name></member>
      <member refid="classtranslator__client_1_1exceptions_1_1ApiValueError_1a7d6f47101d6e223580b0da8c9d8a1954" prot="public" virt="non-virtual"><scope>translator_client::exceptions::ApiValueError</scope><name>__init__</name></member>
      <member refid="classtranslator__client_1_1exceptions_1_1ApiValueError_1ad22c4e5d86cd9b347698e9cb37f6561b" prot="public" virt="non-virtual"><scope>translator_client::exceptions::ApiValueError</scope><name>path_to_item</name></member>
    </listofallmembers>
  </compounddef>
</doxygen>
