<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<doxygen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="compound.xsd" version="1.8.11">
  <compounddef id="classdlg_1_1exceptions_1_1SessionAlreadyExistsException" kind="class" language="Python" prot="public">
    <compoundname>dlg::exceptions::SessionAlreadyExistsException</compoundname>
    <basecompoundref refid="classdlg_1_1exceptions_1_1DaliugeException" prot="public" virt="non-virtual">dlg.exceptions.DaliugeException</basecompoundref>
      <sectiondef kind="private-attrib">
      <memberdef kind="variable" id="classdlg_1_1exceptions_1_1SessionAlreadyExistsException_1a7980d7ebdd330998733cd9bf0a9485f6" prot="private" static="no" mutable="no">
        <type></type>
        <definition>dlg.exceptions.SessionAlreadyExistsException::_session_id</definition>
        <argsstring></argsstring>
        <name>_session_id</name>
        <briefdescription>
        </briefdescription>
        <detaileddescription>
        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="daliuge-common/dlg/exceptions.py" line="109" column="1" bodyfile="daliuge-common/dlg/exceptions.py" bodystart="109" bodyend="-1"/>
      </memberdef>
      <memberdef kind="variable" id="classdlg_1_1exceptions_1_1SessionAlreadyExistsException_1a4c1e863874de1e2e22ddb14d27038987" prot="private" static="no" mutable="no">
        <type></type>
        <definition>dlg.exceptions.SessionAlreadyExistsException::_reason</definition>
        <argsstring></argsstring>
        <name>_reason</name>
        <briefdescription>
        </briefdescription>
        <detaileddescription>
        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="daliuge-common/dlg/exceptions.py" line="110" column="1" bodyfile="daliuge-common/dlg/exceptions.py" bodystart="110" bodyend="-1"/>
      </memberdef>
      </sectiondef>
      <sectiondef kind="public-func">
      <memberdef kind="function" id="classdlg_1_1exceptions_1_1SessionAlreadyExistsException_1a5ca9266225f193b385edace27aee533e" prot="public" static="no" const="no" explicit="no" inline="no" virt="non-virtual">
        <type>def</type>
        <definition>def dlg.exceptions.SessionAlreadyExistsException.__init__</definition>
        <argsstring>(self, session_id, reason=None)</argsstring>
        <name>__init__</name>
        <param>
          <type>self</type>
          <defname>self</defname>
        </param>
        <param>
          <type>session_id</type>
          <defname>session_id</defname>
        </param>
        <param>
          <type>reason</type>
          <defname>reason</defname>
          <defval>None</defval>
        </param>
        <briefdescription>
        </briefdescription>
        <detaileddescription>
        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="daliuge-common/dlg/exceptions.py" line="107" column="1" bodyfile="daliuge-common/dlg/exceptions.py" bodystart="107" bodyend="111"/>
      </memberdef>
      <memberdef kind="function" id="classdlg_1_1exceptions_1_1SessionAlreadyExistsException_1a0d3b601b419eb33a927115dd815ff9fe" prot="public" static="no" const="no" explicit="no" inline="no" virt="non-virtual">
        <type>def</type>
        <definition>def dlg.exceptions.SessionAlreadyExistsException.__str__</definition>
        <argsstring>(self)</argsstring>
        <name>__str__</name>
        <param>
          <type>self</type>
          <defname>self</defname>
        </param>
        <briefdescription>
        </briefdescription>
        <detaileddescription>
        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="daliuge-common/dlg/exceptions.py" line="112" column="1" bodyfile="daliuge-common/dlg/exceptions.py" bodystart="112" bodyend="117"/>
      </memberdef>
      </sectiondef>
    <briefdescription>
    </briefdescription>
    <detaileddescription>
<para><verbatim>An exception thrown when a session ID is pointing to an existing session
but is meant to be used as the ID of a new session.
</verbatim> </para>    </detaileddescription>
    <inheritancegraph>
      <node id="3330">
        <label>Exception</label>
      </node>
      <node id="3328">
        <label>dlg.exceptions.SessionAlreadyExistsException</label>
        <link refid="classdlg_1_1exceptions_1_1SessionAlreadyExistsException"/>
        <childnode refid="3329" relation="public-inheritance">
        </childnode>
      </node>
      <node id="3329">
        <label>dlg.exceptions.DaliugeException</label>
        <link refid="classdlg_1_1exceptions_1_1DaliugeException"/>
        <childnode refid="3330" relation="public-inheritance">
        </childnode>
      </node>
    </inheritancegraph>
    <collaborationgraph>
      <node id="3333">
        <label>Exception</label>
      </node>
      <node id="3331">
        <label>dlg.exceptions.SessionAlreadyExistsException</label>
        <link refid="classdlg_1_1exceptions_1_1SessionAlreadyExistsException"/>
        <childnode refid="3332" relation="public-inheritance">
        </childnode>
      </node>
      <node id="3332">
        <label>dlg.exceptions.DaliugeException</label>
        <link refid="classdlg_1_1exceptions_1_1DaliugeException"/>
        <childnode refid="3333" relation="public-inheritance">
        </childnode>
      </node>
    </collaborationgraph>
    <location file="daliuge-common/dlg/exceptions.py" line="101" column="1" bodyfile="daliuge-common/dlg/exceptions.py" bodystart="101" bodyend="118"/>
    <listofallmembers>
      <member refid="classdlg_1_1exceptions_1_1SessionAlreadyExistsException_1a5ca9266225f193b385edace27aee533e" prot="public" virt="non-virtual"><scope>dlg::exceptions::SessionAlreadyExistsException</scope><name>__init__</name></member>
      <member refid="classdlg_1_1exceptions_1_1SessionAlreadyExistsException_1a0d3b601b419eb33a927115dd815ff9fe" prot="public" virt="non-virtual"><scope>dlg::exceptions::SessionAlreadyExistsException</scope><name>__str__</name></member>
      <member refid="classdlg_1_1exceptions_1_1SessionAlreadyExistsException_1a4c1e863874de1e2e22ddb14d27038987" prot="private" virt="non-virtual"><scope>dlg::exceptions::SessionAlreadyExistsException</scope><name>_reason</name></member>
      <member refid="classdlg_1_1exceptions_1_1SessionAlreadyExistsException_1a7980d7ebdd330998733cd9bf0a9485f6" prot="private" virt="non-virtual"><scope>dlg::exceptions::SessionAlreadyExistsException</scope><name>_session_id</name></member>
    </listofallmembers>
  </compounddef>
</doxygen>
