<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<doxygen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="compound.xsd" version="1.8.11">
  <compounddef id="classtest_1_1apps_1_1test__dynlib2_1_1TestExceptionRaised" kind="class" language="Python" prot="public">
    <compoundname>test::apps::test_dynlib2::TestExceptionRaised</compoundname>
    <basecompoundref prot="public" virt="non-virtual">TestCase</basecompoundref>
      <sectiondef kind="public-func">
      <memberdef kind="function" id="classtest_1_1apps_1_1test__dynlib2_1_1TestExceptionRaised_1ad30b035e72cc2c08feaf29e67c243081" prot="public" static="no" const="no" explicit="no" inline="no" virt="non-virtual">
        <type>def</type>
        <definition>def test.apps.test_dynlib2.TestExceptionRaised.test_exception_print_stats</definition>
        <argsstring>(self)</argsstring>
        <name>test_exception_print_stats</name>
        <param>
          <type>self</type>
          <defname>self</defname>
        </param>
        <briefdescription>
        </briefdescription>
        <detaileddescription>
<para><verbatim>Pass in bad data for the dynlib
</verbatim> </para>        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="daliuge-runtime/test/apps/test_dynlib2.py" line="265" column="1" bodyfile="daliuge-runtime/test/apps/test_dynlib2.py" bodystart="265" bodyend="277"/>
      </memberdef>
      <memberdef kind="function" id="classtest_1_1apps_1_1test__dynlib2_1_1TestExceptionRaised_1a258381af557dd7a70a95bdbee79ff5d9" prot="public" static="no" const="no" explicit="no" inline="no" virt="non-virtual">
        <type>def</type>
        <definition>def test.apps.test_dynlib2.TestExceptionRaised.test_exception_bufsize</definition>
        <argsstring>(self)</argsstring>
        <name>test_exception_bufsize</name>
        <param>
          <type>self</type>
          <defname>self</defname>
        </param>
        <briefdescription>
        </briefdescription>
        <detaileddescription>
<para><verbatim>Pass in bad data for the dynlib
</verbatim> </para>        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="daliuge-runtime/test/apps/test_dynlib2.py" line="278" column="1" bodyfile="daliuge-runtime/test/apps/test_dynlib2.py" bodystart="278" bodyend="288"/>
      </memberdef>
      <memberdef kind="function" id="classtest_1_1apps_1_1test__dynlib2_1_1TestExceptionRaised_1ab01725e65ac909d0624a7af5252d111f" prot="public" static="no" const="no" explicit="no" inline="no" virt="non-virtual">
        <type>def</type>
        <definition>def test.apps.test_dynlib2.TestExceptionRaised.test_exception_memory_error</definition>
        <argsstring>(self)</argsstring>
        <name>test_exception_memory_error</name>
        <param>
          <type>self</type>
          <defname>self</defname>
        </param>
        <briefdescription>
        </briefdescription>
        <detaileddescription>
<para><verbatim>Pass in bad data for the dynlib
</verbatim> </para>        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="daliuge-runtime/test/apps/test_dynlib2.py" line="289" column="1" bodyfile="daliuge-runtime/test/apps/test_dynlib2.py" bodystart="289" bodyend="300"/>
      </memberdef>
      </sectiondef>
    <briefdescription>
    </briefdescription>
    <detaileddescription>
    </detaileddescription>
    <inheritancegraph>
      <node id="3550">
        <label>test.apps.test_dynlib2.TestExceptionRaised</label>
        <link refid="classtest_1_1apps_1_1test__dynlib2_1_1TestExceptionRaised"/>
        <childnode refid="3551" relation="public-inheritance">
        </childnode>
      </node>
      <node id="3551">
        <label>TestCase</label>
      </node>
    </inheritancegraph>
    <collaborationgraph>
      <node id="3552">
        <label>test.apps.test_dynlib2.TestExceptionRaised</label>
        <link refid="classtest_1_1apps_1_1test__dynlib2_1_1TestExceptionRaised"/>
        <childnode refid="3553" relation="public-inheritance">
        </childnode>
      </node>
      <node id="3553">
        <label>TestCase</label>
      </node>
    </collaborationgraph>
    <location file="daliuge-runtime/test/apps/test_dynlib2.py" line="264" column="1" bodyfile="daliuge-runtime/test/apps/test_dynlib2.py" bodystart="264" bodyend="300"/>
    <listofallmembers>
      <member refid="classtest_1_1apps_1_1test__dynlib2_1_1TestExceptionRaised_1a258381af557dd7a70a95bdbee79ff5d9" prot="public" virt="non-virtual"><scope>test::apps::test_dynlib2::TestExceptionRaised</scope><name>test_exception_bufsize</name></member>
      <member refid="classtest_1_1apps_1_1test__dynlib2_1_1TestExceptionRaised_1ab01725e65ac909d0624a7af5252d111f" prot="public" virt="non-virtual"><scope>test::apps::test_dynlib2::TestExceptionRaised</scope><name>test_exception_memory_error</name></member>
      <member refid="classtest_1_1apps_1_1test__dynlib2_1_1TestExceptionRaised_1ad30b035e72cc2c08feaf29e67c243081" prot="public" virt="non-virtual"><scope>test::apps::test_dynlib2::TestExceptionRaised</scope><name>test_exception_print_stats</name></member>
    </listofallmembers>
  </compounddef>
</doxygen>
