<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<doxygen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="compound.xsd" version="1.8.11">
  <compounddef id="namespacedlg_1_1exceptions" kind="namespace" language="Python">
    <compoundname>dlg::exceptions</compoundname>
    <innerclass refid="classdlg_1_1exceptions_1_1DaliugeException" prot="public">dlg::exceptions::DaliugeException</innerclass>
    <innerclass refid="classdlg_1_1exceptions_1_1InvalidDropException" prot="public">dlg::exceptions::InvalidDropException</innerclass>
    <innerclass refid="classdlg_1_1exceptions_1_1InvalidGraphException" prot="public">dlg::exceptions::InvalidGraphException</innerclass>
    <innerclass refid="classdlg_1_1exceptions_1_1InvalidRelationshipException" prot="public">dlg::exceptions::InvalidRelationshipException</innerclass>
    <innerclass refid="classdlg_1_1exceptions_1_1InvalidSessionState" prot="public">dlg::exceptions::InvalidSessionState</innerclass>
    <innerclass refid="classdlg_1_1exceptions_1_1NoDropException" prot="public">dlg::exceptions::NoDropException</innerclass>
    <innerclass refid="classdlg_1_1exceptions_1_1NoSessionException" prot="public">dlg::exceptions::NoSessionException</innerclass>
    <innerclass refid="classdlg_1_1exceptions_1_1SessionAlreadyExistsException" prot="public">dlg::exceptions::SessionAlreadyExistsException</innerclass>
    <innerclass refid="classdlg_1_1exceptions_1_1SubManagerException" prot="public">dlg::exceptions::SubManagerException</innerclass>
    <briefdescription>
    </briefdescription>
    <detaileddescription>
    </detaileddescription>
    <location file="daliuge-common/dlg/exceptions.py" line="1" column="1"/>
  </compounddef>
</doxygen>
